name: Build and Release EXE

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Build with PyInstaller and Inno Setup
        run: cmd /c build.bat

      - name: Get tag name
        id: tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $env:GITHUB_ENV

      - name: Upload installer to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: Output/FVLauncher_Installer.exe
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
